sudo: required

services:
- docker

env:
  global:
  - secure: c9rvP1m/8vGYihEbqVfCLhF6AIGd/vX9LRxf8i99HXMA+os0Q7vQ7DErTacObUX91K1WtRCz69tLtxP2RkXl5YVZt/EwbdBcJeasarWNE0JjNNGqpM7DCPkRUeP+Hm2RSiQ94TrM2Q+pQlujtG1dnw7ErdOKhfJRVMcZBC1MoZkJkOYLsZvmqKmO2z2z4kznsAOxt3VwL2rXS/tLBKfzGwQ3VPJROwdJBXB1FJjxI5rpk0ennTKVeS8x2fru27GjWjttpZwTuJ8cHkrAAtZfrK4FqIWbBhoUfrE8n+1sgu6Onm1HbgzvdUnsYdoGm5W9wmAduK389SpVI9gitNvtky0RKe6ajilzj7Xtpt7mPvld3cpHKODX7NKe1ECjUii0wGZ07ZjLkxJ3BIm/I7COvtixiLX7Ds7Cl6m7Zv7UB1lxz6XO22HXe3AQM3WdRvTFPlLFcA43FFXz5DjGfjDw6Y2d45LHqWpRFObuIytyU3r9mITG3/tvI9pjOLg2WlPGr6wwX86OsfbZC+GuS4N3v55ha/BwUhGHPID0vn/hQ7HLQedXjPEEKiFFiEVf+XF5GLOl9WsFmtBjoPt6OiAN/5BTgCqHIGAs/X2PEX4/e0hICsTS6FxgzaTyrjMnxLQtNef/qMWoqS49pXTNAxNXILKv3/zeEra3UxYJ76DrEDk=
  - secure: bf3zNo6o6fMhTtdthII+cACtIBxHj78hxKMyXFeyZ06zYpcOm50biiWUJPweTdHaAiJFVpsJXc9BUcOqjQwQ6L41ZJT0QtBKSzlsHueJKRyXofbgP6CGnWCrCRokd1qPEXi9hcqb7UzCO4mUObY/Y87eLOre4SHZHkFvhtcUpYJz2ufWMtgm7NuRF9DQKRdLAmaLkNvsaXr+EZNoMUhKf3S8jvYNXu+4kkNu0Lz/xHvVo999O98TA6UmHbnEo9yEAViyiIVwYgkUqJ/yF/UMs95iOSnFZ6FGM2zaIIA2zv923xm5ZuB52+knAw8P4L9eHBHMUYvuPcwsR3y3Z3niKmSJYOHbWlb9Yj2ZMAQH/EjxxCJk2gd8TmmuvgeCx8Tv8/DtrV+MZAsFnb9FvMxamyimb1dnhbteyH6CvmY2enWEOwkuqxDqq/Cl2gg3fd2GGEVXCJECqSBKx6E/9QAidpCtUwQ47fbPYOeugZpCii1LSafa5ZZqylSF72M0/ZvNiSZfha5dUHbft86JibRk2D8DGP43ueEIRZ/5CqyFUQkeLBc+fZrwHaqmSew5hPYJw098PYV7gq8i/fi/DCNFHbdnj+8P1qvMyhY3mZRQvDkiCX6ARJkWQeb8e0zrtNSSv2CFM6QRiTSSc0Z4w+PmG8kcJ8a+J42D5EBeZuk8bZ4=
  - secure: g+fLMcGV9P1bYgRUWZQPls2lxCjmQzxq/c+oYZmJrDpeBQlcmlYms56wSzZiRMjdWD8O7UArZy+Qj//Y+7wrKj9K9Tml+lGBZZgPIz34rKYMAkehesEa+kaVSZqKA6JBRdlKfFcted4DiWDJ9YhKHulBiqqBZa6JDhe4EYXHHwJvhdzJlLichv9EdhhfNFJMlbXkdPZTrA5aUjgDZUqBCaAQd1ncw5X3a8eEO8CsWT6j2BosWC22QdU3cGFcOW5v/FqxqdGmdzwFeAPzitVBQcbpno5snSqUta0dKPlH7vxWi4yN8eORuTKRxbvJzDxNb0tjE3AnWcQQX63QOCiw1qXMcWFqd00NCsVJRT0M2ws1SxU2eTjHKoepodb8uR7+gOW0QFetBfsXnaSOjxKyi6/obggPYmd7BwqcxKZea6mVOGKWVQc2Gu2EzX/OLz8dqqhKFMSkr8GLkUvMpHk+fwzjKaM8dYGxgxqqN6MsicnpKbzqfd59FDOjdNPAGyJlxVLUaKnAlGR4bL4BwNfTbdphfO/68r3f2HA7spUbVkqze3hnrDV1P4gW2NvecQjm96/Nw37w3jijHLaBIxc+WmA4h9y0s4fK/c9tVkEhG1tooJuDd9i2a/b2pER4WhzFChdi1nvWSuaTdETgJzozBmstEJA5ys56mG5hN1sAczo=
  - COMMIT=${TRAVIS_COMMIT::8}
  
install:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=elfolink/spark
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
